services:
  server:
    # docker compose run --no-TTY server
    image: server
    build:
      context: .
      target: server
      platforms:
        - wasi/wasm32
    runtime: io.containerd.wasmedge.v1
    network_mode: host
    ports:
      - 8080:8080
