name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown
          cargo check --target wasm32-unknown-unknown

      - name: Toolchain info
        run: |
          cargo --version --verbose

      - name: hello_world
        run: |
          cd hello_world
          cargo build

      - name: hello_world_wasm
        run: |
          cd ..
          cd hello_world_wasm
          cargo build --target wasm32-unknown-unknown --release       
