name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown

      - name: hello_world
        run: |
          cd hello_world
          cargo build

      - name: hello_world_wasm_web
        run: |
          cd hello_world_wasm_web
          cargo check --target wasm32-unknown-unknown
          cargo build --target wasm32-unknown-unknown --release       

      - name: hello_world_wasmjs_web
        run: |
          cd hello_world_wasmjs_web
          cargo install wasm-pack
          wasm-pack build --target web   

      - name: rust_euler
        run: |
          cd rust_euler
          cargo test
