name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown

      - name: hello_world
        run: |
          cd hello_world
          cargo build

      - name: hello_world_wasm
        run: |
          cd hello_world_wasm
          cargo check --target wasm32-unknown-unknown
          cargo build --target wasm32-unknown-unknown --release       
